### ISSUE TITLE
Question. How to control infinity repeated jobs?

### ISSUE THREAD

**Issue by m-pokrovskii** [vsivsi/meteor-job-collection-playground#2]
How to control infinity repeated jobs? Such as stopping them, modifying and monitoring the process?

**Comment by vsivsi** [comment]
This is a demo app. You may stop them simply but using the stop control.  This app doesn't allow you modify jobs.  Please see the main job-collection repo for answers to your other questions.

https://atmospherejs.com/vsivsi/job-collection
